package subvoyage.content.other;

import arc.graphics.*;


public class SvPal {
    public static Color
    outline = Color.valueOf("191820").a(1f),
    teslaCharge = Color.valueOf("ffee94"),
    photoFlash = Color.valueOf("eceeff"),
    spaclanium = Color.valueOf("D8C4FF"),
    corallite = Color.valueOf("81AA72"),
    sulfur = Color.valueOf("C4A981"),
    sand = Color.valueOf("F7CBA4"),
    iridium = Color.valueOf("6C7181"),
    clay = Color.valueOf("B28768"),
    crude = Color.valueOf("393f42"),
    chromium = Color.valueOf("8E898B"),
    nitride = Color.valueOf("E59374"),
    phosphide = SvPal.spaclanium.cpy().lerp(SvPal.iridium,0.3f),
    tugSheet = Color.valueOf("72817d"),
    quartzFiber = Color.valueOf("f4cec2"),
    heatGlow = Color.valueOf("feb380"),
    inspirationLaser = Color.valueOf("FF4023"),
    chromiumLightish = Color.valueOf("d5cba3"),
    chromiumMid = Color.valueOf("5f4b5b"),
    tugSheetLightish = Color.valueOf("95b3b1"),
    turretHeatGlow = Color.valueOf("ffffc4"),
    tugSheetGlow = Color.valueOf("bee8d7"),
    clayDarkish = Color.valueOf("54333c"),
    veryDarkViolet = Color.valueOf("1b1a1d"),
    argonFlame = Color.valueOf("bd4453"),
    argonMidSmelt = Color.valueOf("ff8c99"),
    quartzWeave = Color.valueOf("fde8e2"),
    toxicExplosion = Color.valueOf("e7e789"),
    energyLaser = Color.valueOf("D9F2FF"),
    polygen = Color.valueOf("A5A3FF"),
    hardWater = Color.valueOf("5a78b3"),
    argon = Color.valueOf("FF8C99"),
    propane = Color.valueOf("E2992D"),
    helium = Color.valueOf("C1D0CA"),
    nitrogen = Color.valueOf("E7E1B9"),
    suppresion = Color.valueOf("FE6C4C"),
    atlacianIcon = Color.valueOf("7286AD"),
    atlacianAtmosphere = Color.valueOf("5177FF"),
    atlacianLandCloud = Color.valueOf("4F4CB5"),
    atlacianOcean = Color.valueOf("4265AF"),
    legartyte = Color.valueOf("125C5F"),
    legartyteLightish = Color.valueOf("137B6D"),
    agaryte = Color.valueOf("314544"),
    danger = Color.valueOf("FF5E5E"),
    hydromech = Color.valueOf("A6E8DF"),

    laserGrey = Color.valueOf("8E4847"),
    laserRed = Color.valueOf("FF5451"),
    laserGreen = Color.valueOf("72FF77"),
    laserBlue = Color.valueOf("263FFF"),
    laserViolet = Color.valueOf("7F30FF")
    ;
}
